package:
  name: "frmodel"
  version: "0.0.6"

source:
  path: ../src

build:
  script: python setup.py install

requirements:
  build:
    - pillow
    - opencv
    - pandas
    - numpy
    - python
    - scipy
    - scikit-image
    - scikit-learn
    - tqdm
    - utm
  run:
    - pillow
    - opencv
    - pandas
    - numpy
    - python
    - scipy
    - scikit-image
    - scikit-learn
    - tqdm
    - utm


about:
  home: "https://github.com/Eve-ning/frmodel"
  summary: "Forest Recovery Modelling base library"
  doc_url: https://eve-ning.github.io/frmodel/
  dev_url: https://github.com/Eve-ning
  license: Mozilla Public License 2.0
  license_file: ../LICENSE

